### ISSUE TITLE
Why does this function handle the token this way?

### ISSUE THREAD

**Issue by jennybc** [jennybc/gspreadr#16]
I'm working on something else but this caught my eye. Not sure I understand your handling of the token here:

https://github.com/jennybc/gspreadr/blob/master/R/http-requests.R#L79-L84

What is the relationship of the formal argument `token` to anything else?

**Comment by jzhaoo** [comment]
I wanted to let users open public spreadsheets without needing to authenticate. I think I changed the code to handle that but didn't remove the `token` parameter in the function. It shouldn't be there.

**Comment by jennybc** [comment]
OK please fix and push to master. I'll deal with merging in. I'm trying hard to get something pushed very soon so we can go back to co-development.

**Comment by jzhaoo** [comment]
Fixed in ec6d28fc73f6f9d5f57078ea8b6f33b9ebf91551
