### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by sckott** [jennybc/gspreadr#2]
For me, trying `authorize()` naively has `new_user = FALSE`, and when that's run, a new tab opens in default browser, but then just hangs. Would it be possible to prevent this?  Perhaps if there is no `.httr-oauth`, then do auth flow?

**Comment by jennybc** [comment]
@jzhaoo Things have changed so much since this was opened. Is this still an issue?

**Comment by jennybc** [comment]
ping @jzhaoo 

safe to close this?
