### ISSUE TITLE
Maximize usage of httr for building and modifying URLs

### ISSUE THREAD

**Issue by jennybc** [jennybc/gspreadr#21]
Refactor and/or eliminate `build_req_url()`. Once I push you can see at least one instance of me using `httr::modify_url()` to add query parameters to the cell feed.

**Comment by jennybc** [comment]
I think this is fairly high priority.

**Comment by jzhaoo** [comment]
Eliminated `build_req_url()` in #31

**Comment by jennybc** [comment]
I think we have successfully changed our *modus operandi* here. Keep up the good work @jzhaoo re: taking maximum advantage of `httr`.
