### ISSUE TITLE
Vector matching in `gsheets_auth()`

### ISSUE THREAD

**Issue by sckott** [jennybc/gspreadr#3]
In that function, this line https://github.com/jennybc/gspreadr/blob/master/R/auth.R#L102 `if(class(token) != "character")` matches against a token object, and  I get

```r
class(token)
[1] "Token2.0" "Token"    "R6" 
```

Causes warning because of matching against more than one thing

```r
Warning message:
In if (class(token) != "character") auth <- config(token = .state$token) else auth <- add_headers(Authorization = .state$token) :
  the condition has length > 1 and only the first element will be used
```

**Comment by jennybc** [comment]
I just got the same message. How did I get it?

```r
> library(gspreadr)
> browseVignettes("gspreadr")
> # run a line of code from the vignette, which triggers authentication in the browser
> pub_sheet <- open_by_key("1WNUDoBbGsPccRkXlLqeUK9JUQNnqq2yvc9r7-cmEaZU")
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Warning message:
In if (class(token) != "character") auth <- config(token = .state$token) else auth <- add_headers(Authorization = .state$token) :
  the condition has length > 1 and only the first element will be used
```

**Comment by jennybc** [comment]
@sckott 

Is there some sort of glitch in the matrix here? Above it looks like you've committed to this repo, but in fact you have not and, I would think, can not. Huh?

**Comment by sckott** [comment]
@jennybc gosh, no idea what's going on there. i did make some changes, but I thought I committed them to a fork on my account, then i think i deleted my fork - I don't see that commit in the commit logs of this repo

**Comment by jennybc** [comment]
This function doesn't even exist any more.
