### ISSUE TITLE
login() needs to be modified to run tests to talk to Drive API

### ISSUE THREAD

**Issue by jzhaoo** [jennybc/gspreadr#30]
Current login() function can only talk to Sheets API so functions talking to Drive API will return 401 ERROR - Unauthorized. Since login() is used for authentication in tests, cant run tests for new/delete/copy ss.

**Comment by jzhaoo** [comment]
If service is changed to "writely" , https://github.com/jennybc/gspreadr/blob/master/R/auth.R#L17, 

, user can successfully authorize to access the "Documents List Data API" but sadly wouldn't work with the new Google Drive API. A `403 Forbidden ERROR` is returned when trying to make requests. login() cant talk to Drive API.

**Comment by jennybc** [comment]
Does the "Documents List Data API" do us any good? Can you state clearly what the two APIs do and which we need?

We really should look into encrypting a `.httr-oaut` file and using that on Travis instead of the username/password ….

**Comment by jennybc** [comment]
Can you please look at the "Skipping a test" section here:

http://r-pkgs.had.co.nz/tests.html

and write a similar function that detects whether we're authenticated via OAuth or login? We need that functionality BTW. Then use it to write a custom skipper which will be more focused than the current `skip()`s you are using of the spreadsheet adding and deleting tests.

**Comment by jzhaoo** [comment]
The [Documents Data List API](https://developers.google.com/google-apps/documents-list/) is replaced by the Drive API and will no longer be supported after April 20, 2015. The Drive API covers all functionality of the Documents Data List API. 

http://googleappsdeveloper.blogspot.ca/2012/09/retiring-google-documents-list-api-v3.html

I don't think it is worth the effort to make another version of the "drive" functions in order to make calls to the Documents Data List API since they soon won't work anyways.

**Comment by jennybc** [comment]
I have reworked authentication during testing.

https://github.com/jennybc/gspreadr/blob/master/tests/testthat/helper02_login.R

In particular, we are now using OAuth almost always. In theory it will be always on local machines. So we only authenticate via login on Travis and I've written a custom skipper so we're skipping as few things as possible and only where truly necessary.

**Comment by jennybc** [comment]
Can we close this? We're not going to modify login, right? And we're testing via OAuth2 whenever possible. And we're skipping the minimum number of functions on Travis, i.e. the ones that call the Drive API.

I don't think we have any more plans on this front, right? If you agree, @jzhaoo, please close.
