### ISSUE TITLE
Unable to register other's spreadsheets by URL only

### ISSUE THREAD

**Issue by jzhaoo** [jennybc/gspreadr#36]
Right now, unless the sheet is already in your Google Sheets home screen listing,  you can only register someone else's spreadsheet by using the `key` argument and can't just be lazy and use the entire URL without specifying the key. Is this what we are sticking with? If so, then the documentation for `register()` should maybe be updated to reflect that?

**Comment by jennybc** [comment]
This usage gap is now fixed via 2412885f89e65f2d1b5060955d6b6ad44b5f67f2. If user wants to register a spreadsheet that does not appear in Sheets home screen, it's now possible to provide the URL and specify `verify = FALSE` to `identify_ss()`. This will form a skeletal spreadsheet object that holds the key and worksheets feed, which can then be used to (attempt to) register the sheet.

**Comment by jzhaoo** [comment]
`verify = FALSE

**Comment by jennybc** [comment]
My mind is elsewhere right now but I think the workflow I had in mind in this case was to call `identify_ss()` then pass the result of that to `register_ss()`.

But you might be right about adding `verify =` to `register_ss()` as well. I'll have to think about it.
