### ISSUE TITLE
Troubles with encodings

### ISSUE THREAD

**Issue by mbojan** [jennybc/gspreadr#45]
I have published a public spreadsheet with some Polish characters I am having trouble importing via your awesome package. Here is a snippet to reproduce the problem:

```{r}
# with url
u <- "https://docs.google.com/spreadsheets/d/1c4Cgbs1BvbxutPYhDK36QibqHoWy8zcqKm2LARWGwmk/edit?usp=sharing"
enc <- register_ss(u)
d <- get_via_lf(enc)
d
# Source: local data frame [9 x 3]
# 
#   numbers letters letterspl
# 1       1       a   Ä\u0085
# 2       2       c   Ä\u0087
# 3       3       e   Ä\u0099
# 4       4       l   Å\u0082
# 5       5       n   Å\u0084
# 6       6       o        Ã³
# 7       7       s   Å\u009b
# 8       8       z        Åº
# 9       9       z        Å¼
```

**Comment by mbojan** [comment]
screenshot of the spreadsheet (just in case)

![sheet](https://cloud.githubusercontent.com/assets/636574/6697237/88cc49f0-ccef-11e4-80c3-58e522da443a.png)

**Comment by jennybc** [comment]
@mbojan We think we've handled this, but let me know if we're wrong about that!
