### ISSUE TITLE
Underscores are dropped from variable names

### ISSUE THREAD

**Issue by mbojan** [jennybc/gspreadr#46]
See #45 and a screenshot where `letters_pl` become `letterspl` in the imported data frame.

**Comment by jennybc** [comment]
This is actually a "feature" of the Sheets API itself. It's not our doing. In the Google Sheets API docs, in the section on [Working with list-based feeds](https://developers.google.com/google-apps/spreadsheets/#working_with_list-based_feeds), there's this:

> The column names are the header values of the worksheet lowercased and with all non-alpha-numeric characters removed.

So I think the only thing we can and will do about this is to add something to the documentation for `get_via_lf()`.

I would imagine that consumption via the cell feed (`get_via_cf()` + reshaping) will preserve column headers, but this is slower. For small/medium sheets, it shouldn't be that noticeable.

**Comment by jennybc** [comment]
Added something to documentation of `get_via_lf()` about this. 5594332882005dd455eb4e52d969d240c0925dc7

**Comment by mbojan** [comment]
Makes sense. Rightfully closed.
