### ISSUE TITLE
Login using email and password will be shut down

### ISSUE THREAD

**Issue by jzhaoo** [jennybc/gspreadr#49]
According to [Google](https://developers.google.com/accounts/docs/AuthForInstalledApps), 

> Important: ClientLogin has been officially deprecated as of April 20, 2012. It will be shut down on April 20, 2015 as per our deprecation policy. We encourage you to migrate to OAuth 2.0 as soon as possible.

Remove this authorization option now? @jennybc

**Comment by jennybc** [comment]
Sure seems reasonable. BTW I am working on the PR re: cell editing, just haven't pushed or merged yet ….

**Comment by jennybc** [comment]
When you remove this functionality, please root out all mentions of authentication via username/password, e.g. in the README and vignette, and delete them too.

**Comment by jennybc** [comment]
Done in f5eb3394ca632608be0bc3f0c5acdef38163a857
