### ISSUE TITLE
Error in edit_cells due to CRAN stringr

### ISSUE THREAD

**Issue by noamross** [jennybc/gspreadr#57]
While running the vingette, I get the following error

```
> foo <- foo %>% edit_cells(input = head(iris), header = TRUE)
Error: 'str_to_upper' is not an exported object from 'namespace:stringr'
```

This appears to be because I am using the CRAN version of stringr (0.6.2).  The error does not appear when I use the github version (0.9.0.9).  I'm not sure when Hadley is planning on updating CRAN's stringr (I note it has been several years), but it might make sense to avoid this dependency (or at least note it in the README).

**Comment by jennybc** [comment]
Good point. I think there are other functions that use things in the github version of `stringr` vs CRAN. I should do a proper check and figure out the feasibility of just using CRAN version of `stringr`.

**Comment by noamross** [comment]
I'm a `stringi` partisan myself, and I note that most of what you might get in the github `stringr` can be found in `stringi`, e.g.,

```
> library(stringr)
> str_to_upper
function (string, locale = "") 
{
    stri_trans_toupper(string, locale = locale)
}
<environment: namespace:stringr>
```
