### ISSUE TITLE
gspreadr-package.Rd issues

### ISSUE THREAD

**Issue by leeper** [jennybc/gspreadr#6]
I get `All text must be in a section` warnings because of [lines 32-33 in gspreadr-package.Rd](https://github.com/jennybc/gspreadr/blob/master/man/gspreadr-package.Rd#L32-L33). The file still has the original contents from `package.skeleton()` that fail R CMD check.

**Comment by jennybc** [comment]
The changes/fixes in the recent reboot supersede this.
