### ISSUE TITLE
edit_cells not working (update: currently requires stringr from github)

### ISSUE THREAD

**Issue by markriseley** [jennybc/gspreadr#72]
I tried to run the "edit_cells" code example and it falls over. Here's a copy paste from the R console.
I have successfully authenticated and managed to read and create spreadsheets. I Google Drive the new ss "yo" exists but is empty.

    > yo <- new_ss("yo")
    Sheet "yo" created in Google Drive.
    Identifying info is a gspreadsheet object; gspreadr will re-identify the sheet based on sheet key.
    Sheet identified!
    sheet_title: yo
    sheet_key: 1nP_oqLvOSUiY-m5syx0IwELXrX5ZMaywx8He6ZIKv1Q
    
    > yo <- edit_cells(yo, input = head(iris), header = TRUE, trim = TRUE)
    Error: x <= letter_to_num("ZZ") are not all TRUE
    In addition: Warning message:
    In function_list[[i]](value) : NAs introduced by coercion

Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.99.283)          
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London

**Comment by jennybc** [comment]
My student got the same message when he ran the README code yesterday, so it's not just you. He's also on Windows, as I suppose you are? I'll be able to look into this tonight. thanks.

**Comment by markriseley** [comment]
Yes windows 8.1.

Thanks for building this package, a great idea!

**Comment by sfirke** [comment]
Same issue here.  Windows 8.1.  Really excited to use this package!

**Comment by jennybc** [comment]
@markriseley @sfirke @daattali

Can you all tell me the version of `stringr` you are using? I suspect `gspreadr` is currently using functionality from the devel / GitHub version of `stringr`. And I bet you're running the CRAN release or a GitHub version from … before December 2014?

**Comment by daattali** [comment]
0.6.2
I do think it's the one from CRAN. Which means it's over 2 years old....?
On CRAN it says it was published 2012-12, I don't know if that means
original publish date or most updated version..

On Thu, Mar 26, 2015 at 11:01 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> @markriseley <https://github.com/markriseley> @sfirke
> <https://github.com/sfirke> @daattali <https://github.com/daattali>
>
> Can you all tell me the version of stringr you are using? I suspect
> gspreadr is currently using functionality from the devel / GitHub version
> of stringr. And I bet you're running the CRAN release or a GitHub version
> from … before December 2014?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/gspreadr/issues/72#issuecomment-86836059>.
>



-- 
http://deanattali.com

**Comment by jennybc** [comment]
@daattali If you're willing to install `stringr` from GitHub, I'd be very interested to hear if the `edit_cells()` problem goes away. I am at a hotel w/ WiFi that is preventing me from easily checking certain aspects of this myself right this moment...

**Comment by daattali** [comment]
Yeah I'll try that when I can. GitHub has been very unstable today and I
can't seem to connect to it now.  R people show up at GitHub --> GitHub
goes down.... coincidence?

On Thu, Mar 26, 2015 at 11:09 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> @daattali <https://github.com/daattali> If you're willing to install
> stringr from GitHub, I'd be very interested to hear if the edit_cells()
> problem goes away. I am at a hotel w/ WiFi that is preventing me from
> easily checking certain aspects of this myself right this moment...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/gspreadr/issues/72#issuecomment-86837574>.
>



-- 
http://deanattali.com

**Comment by daattali** [comment]
@jennybc after installing stringr 0.9.0.9000, edit_cells works. One thing
off your mind.

On Thu, Mar 26, 2015 at 11:26 PM, Dean Attali <daattali@gmail.com> wrote:

> Yeah I'll try that when I can. GitHub has been very unstable today and I
> can't seem to connect to it now.  R people show up at GitHub --> GitHub
> goes down.... coincidence?
>
> On Thu, Mar 26, 2015 at 11:09 PM, Jennifer (Jenny) Bryan <
> notifications@github.com> wrote:
>
>> @daattali <https://github.com/daattali> If you're willing to install
>> stringr from GitHub, I'd be very interested to hear if the edit_cells()
>> problem goes away. I am at a hotel w/ WiFi that is preventing me from
>> easily checking certain aspects of this myself right this moment...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jennybc/gspreadr/issues/72#issuecomment-86837574>.
>>
>
>
>
> --
> http://deanattali.com
>



-- 
http://deanattali.com

**Comment by jennybc** [comment]
@daattali I can get the exact same error message if I artificially introduce the problem that the CRAN vs devel version of `stringr` causes. Can't access Google Sheets or push to GitHub/Travis now to verify. But quite sure this is it.

**Comment by markriseley** [comment]
devel stringr solves it for me.

**Comment by jennybc** [comment]
I'm going to rewrite the function in question to NOT require devel `stringr` as the proper fix for this. Will update and close this when done. Thanks for bringing this to my attention.
