### ISSUE TITLE
Additional functions in gspread not in README

### ISSUE THREAD

**Issue by jzhaoo** [jennybc/gspreadr#8]
These functions were found in [models.py](https://github.com/burnash/gspread/blob/master/gspread/models.py) but not introduced in the README. 

- insert_row
- append_row
- add_rows
- add_cols
- resize

**Comment by jzhaoo** [comment]
resize_worksheet implemented in 4190c01bc975ccfd4e2b8413608643e7e8e435a3.
add_rows and add_cols, implemented in 2a547292ced5122fbfb7bcc4b977487f01b5ca2a.

**Comment by jennybc** [comment]
I think we're good on this front. If there's functionality along these lines that's still needed, I'm sure we'll find out.
